# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95f65414afba53560b17b2d603264959"
name = "lma-private-app"
handle = "lma-private-app"
application_url = "https://551d-2603-9000-f9f0-8f50-c2a-af85-6d37-bea4.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
dev_store_url = "alexs-store-43123.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_metaobjects,read_products,write_customers,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://551d-2603-9000-f9f0-8f50-c2a-af85-6d37-bea4.ngrok-free.app/auth/callback",
  "https://551d-2603-9000-f9f0-8f50-c2a-af85-6d37-bea4.ngrok-free.app/auth/shopify/callback",
  "https://551d-2603-9000-f9f0-8f50-c2a-af85-6d37-bea4.ngrok-free.app/api/auth/callback"
]

[app_proxy]
subpath = "lma"
prefix = "apps"
url = "https://551d-2603-9000-f9f0-8f50-c2a-af85-6d37-bea4.ngrok-free.app/proxy"

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
