# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95f65414afba53560b17b2d603264959"
name = "lma-private-app"
handle = "lma-private-app"
application_url = "https://knee-computing-extent-online.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
dev_store_url = "alexs-store-43123.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_metaobjects,read_products,write_customers,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://knee-computing-extent-online.trycloudflare.com/auth/callback",
  "https://knee-computing-extent-online.trycloudflare.com/auth/shopify/callback",
  "https://knee-computing-extent-online.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
