# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5b15939c7e71977b6dd507b68379589"
name = "Latin Mix Academy Dev"
handle = "lma-private-app-dev"
application_url = "https://955f-2603-9000-f9f0-8f50-c89c-9cc2-2b30-da3.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
dev_store_url = "alexs-store-43123.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_metaobjects,read_products,write_customers,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://955f-2603-9000-f9f0-8f50-c89c-9cc2-2b30-da3.ngrok-free.app/auth/callback",
  "https://955f-2603-9000-f9f0-8f50-c89c-9cc2-2b30-da3.ngrok-free.app/auth/shopify/callback",
  "https://955f-2603-9000-f9f0-8f50-c89c-9cc2-2b30-da3.ngrok-free.app/api/auth/callback"
]

[app_proxy]
subpath = "lma"
prefix = "apps"
url = "https://955f-2603-9000-f9f0-8f50-c89c-9cc2-2b30-da3.ngrok-free.app/proxy"

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
