# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95f65414afba53560b17b2d603264959"
name = "lma-private-app"
handle = "lma-private-app"
application_url = "https://3036-2603-9000-f9f0-8f50-a4e9-5597-245a-ce92.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alexs-store-43123.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_metaobjects,read_products,write_customers,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://3036-2603-9000-f9f0-8f50-a4e9-5597-245a-ce92.ngrok-free.app/auth/callback",
  "https://3036-2603-9000-f9f0-8f50-a4e9-5597-245a-ce92.ngrok-free.app/auth/shopify/callback",
  "https://3036-2603-9000-f9f0-8f50-a4e9-5597-245a-ce92.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
